### ISSUE TITLE
docker-compose build failing for proxy container

### ISSUE THREAD

**Issue by vishveshg** [shlomizadok/foreman-docker-compose#12]
Repo URL: https://github.com/shlomizadok/foreman-docker-compose.git
SHA: 995b90b286520173ea11e4b8f696cd90c5568ae5
Steps:
1. cd foreman-docker-compose
2. docker-compose build

Output:
Building proxy
Step 1/9 : FROM fedora:latest
 ---> d7372e6c93c6
Step 2/9 : LABEL MAINTAINER="shlomi@ben-hanna.com"
 ---> Using cache
 ---> 14ca16b07d10
Step 3/9 : RUN dnf -y update
 ---> Using cache
 ---> 3c2056269408
Step 4/9 : RUN dnf -y install     ruby{,-devel,gems,-irb}     rubygem-{nokogiri,bundler,unf_ext,rdoc}     redhat-rpm-config     nodejs     postgresql-devel     git     gcc-c++     make     hostname  && dnf clean all
 ---> Using cache
 ---> 89b19d4c3e23
Step 5/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 4071b07fd07d
Step 6/9 : ENV REPO_URL=https://github.com/theforeman/smart-proxy.git
 ---> Using cache
 ---> a63bcee8256a
Step 7/9 : RUN git clone --depth=1 ${REPO_URL} .  && mkdir logs
 ---> Using cache
 ---> 234dfc3bd595
Step 8/9 : RUN bundle --without bmc:krb5:libvirt:puppet_proxy_legacy:test:windows
 ---> Running in a9314a38373d
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Your Gemfile lists the gem rsec (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem single_test (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem rdoc (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
The dependency highline (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32`.
The dependency win32-service (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32`.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching rake 12.3.2
Installing rake 12.3.2
Using bundler 1.16.1
Fetching coderay 1.1.2
Installing coderay 1.1.2
Fetching concurrent-ruby 1.1.4
Installing concurrent-ruby 1.1.4
Fetching ffi 1.10.0
Installing ffi 1.10.0 with native extensions
Fetching journald-native 1.0.11
Installing journald-native 1.0.11 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/share/gems/gems/journald-native-1.0.11/ext/journald_native
/usr/bin/ruby -r ./siteconf20190309-1-9ax80q.rb extconf.rb
checking for systemd/sd-journal.h... no
checking for -lsystemd... no
checking for sd_journal_print()... no
checking for -lsystemd-journal... no
checking for sd_journal_print()... no
creating extconf.h
creating Makefile

current directory:
/usr/share/gems/gems/journald-native-1.0.11/ext/journald_native
make "DESTDIR=" clean
rm -f 
rm -f journald_native.so  *.o  *.bak mkmf.log .*.time

current directory:
/usr/share/gems/gems/journald-native-1.0.11/ext/journald_native
make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.
-DRUBY_EXTCONF_H=\"extconf.h\" -I/usr/include    -fPIC -O2 -g -pipe -Wall
-Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
-fexceptions -fstack-protector-strong -grecord-gcc-switches
-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic
-fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC
-std=c11 -m64 -o journald_dummy.o -c journald_dummy.c
In file included from journald_dummy.c:1:
journald_native.h:37:14: error: #error Cannot include <systemd/sd-journal.h>.
Please use linux version with systemd-journal installed
#error Cannot include <systemd/sd-journal.h>. Please use linux
version with systemd-journal installed
              ^~~~~
journald_native.h:41:14: error: #error Required function sd_journal_print is
missing
             #error Required function sd_journal_print is missing
              ^~~~~
journald_native.h:45:14: error: #error Required function sd_journal_sendv is
missing
             #error Required function sd_journal_sendv is missing
              ^~~~~
journald_native.h:49:14: error: #error Required function sd_journal_perror is
missing
             #error Required function sd_journal_perror is missing
              ^~~~~
journald_native.h:55:18: fatal error: systemd/sd-journal.h: No such file or
directory
         #include <systemd/sd-journal.h>
                  ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:243: journald_dummy.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/share/gems/gems/journald-native-1.0.11
for inspection.
Results logged to /usr/lib64/gems/ruby/journald-native-1.0.11/gem_make.out

An error occurred while installing journald-native (1.0.11), and Bundler cannot
continue.
Make sure that `gem install journald-native -v '1.0.11'` succeeds before
bundling.

In Gemfile:
  logging-journald was resolved to 2.0.3, which depends on
    journald-logger was resolved to 2.0.4, which depends on
      journald-native
ERROR: Service 'proxy' failed to build: The command '/bin/sh -c bundle --without bmc:krb5:libvirt:puppet_proxy_legacy:test:windows' returned a non-zero code: 5

**Comment by iahmad-khan** [comment]
Same issue running on docker Desktop for MAC , maybe I need to run it on Fedora or RHEL

**Comment by bittner** [comment]
In theory this should be working on all mainstream OSes. I had this working on Ubuntu 16.10 and now on Ubuntu 18.04, it even runs on a Synology NAS DS918+ (which runs some sort of crippled pseudo-Debian distribution).

I'd guess the [journald-native Gem](https://rubygems.org/gems/journald-native/versions/1.0.11) breaks in the latest version. Note the error message that says, "Please use linux version with systemd-journal installed". We may need to install a _systemd-journal_ dev package providing the header files.

Not sure which package on Fedora this provides. A web search didn't reveal anything substantial for Fedora. The missing packe (if any) would be needed to be added to the [list of installed packages](https://github.com/shlomizadok/foreman-docker-compose/blob/master/proxy/Dockerfile#L6-L15) then.

**Comment by iahmad-khan** [comment]
Not even working on latest fedora , need to add systemd-devel inside the dockerfile
